version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8503:8503"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - BASE_URL=http://192.168.4.255:8000/
    networks:
      - streamlit-net

networks:
  streamlit-net:
    driver: bridge